#!/bin/bash
set -e

# AES New Project Scaffolding
# Creates a new project with AES structure

PROJECT_NAME=$1
LANGUAGE=${2:-python}

if [ -z "$PROJECT_NAME" ]; then
  echo "❌ Usage: make new-project NAME=project-name [LANGUAGE=python]"
  echo "   or: ./scripts/new-project.sh project-name [language]"
  echo ""
  echo "Supported languages:"
  echo "  python, javascript, go, rust, java, php"
  exit 1
fi

echo "🏗️  Scaffolding new AES project: $PROJECT_NAME (language: $LANGUAGE)"
echo ""

# Validate name (alphanumeric, dash, underscore)
if [[ ! "$PROJECT_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "❌ Project name must be alphanumeric with dashes/underscores"
  exit 1
fi

# Check if directory exists
if [ -d "$PROJECT_NAME" ]; then
  echo "❌ Directory '$PROJECT_NAME' already exists"
  exit 1
fi

# Create directory structure
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

mkdir -p docs
mkdir -p src
mkdir -p tests
mkdir -p .github/workflows
mkdir -p .aes/plugins

# Copy and customize VISION.md (replace placeholders)
cat > docs/VISION.md <<EOF
# Vision

## Problem

[Describe the problem you're solving. Who is hurt by this? What happens if not solved?]

## Solution

[Describe your approach. How does it solve the problem? What makes it different?]

## Value

[Why this matters. Impact metrics. Success criteria.]
EOF

# Copy and customize PERSONAS.md
cat > docs/PERSONAS.md <<EOF
# Personas

## User

**Profile:** [Describe your user]

**Goals:**
- Goal 1
- Goal 2

**Needs:**
- Need 1
- Need 2

**Pain Points:**
- Pain 1
- Pain 2

## Maintainer

**Profile:** Engineer maintaining this codebase

**Goals:**
- Keep code clean and documented
- Ensure quality without friction

**Needs:**
- Clear testing strategy
- Automated quality gates
- Easy onboarding

**Tools:**
- AES (Aggressive Engineering System)
- \`make check\` for validation
EOF

# Copy and customize REQUIREMENTS.md
cat > docs/REQUIREMENTS.md <<EOF
# Requirements

## Functional

- [Feature 1 description]
- [Feature 2 description]

## Non-Functional

- Performance: [target]
- Security: [requirements]
- Maintainability: [guidelines]

## Constraints

- Language: $LANGUAGE
- Deployment: [target]
- Dependencies: [list]
EOF

# Copy and customize ROADMAP with first task
cat > docs/ROADMAP.md <<EOF
# Roadmap

## [HIGH] Initial Setup
- Impact: High
- Effort: Low
- Status: done

## [MEDIUM] First Feature
- Impact: Medium
- Effort: Medium
- Status: todo

## [LOW] Polish & Refine
- Impact: Low
- Effort: Low
- Status: todo

---
*Generated by AES scaffolding*
EOF

# Create base task template
mkdir -p docs/TASKS
cat > docs/TASKS/01-initial-setup.md <<'EOF'
# Task: Initial project setup

## Goal
Establish working project with AES quality gates passing.

## Hostile Analysis
- What assumptions are we making about the runtime?
- What could break in deployment?
- Is this the simplest way to achieve the goal?
- Are there dependencies that could cause issues?

## Proposed Solution
1. Follow language-specific setup guide
2. Write simple "hello world" to verify toolchain
3. Ensure `make check` passes

## Surgical Plan
1. Create minimal src/main.$LANG → verify: compiles/imports
2. Create tests → verify: `make test` passes (or skips gracefully)
3. Configure linter/formatter → verify: `make lint` passes
4. Update docs with actual tool versions → verify: `make doctor` shows no issues

## Validation
- [ ] Project builds without errors
- [ ] `make check` passes (or allows TODOs for unimplemented features)
- [ ] All docs exist and are filled (VISION, PERSONAS, REQUIREMENTS, ROADMAP)
- [ ] Git initialized, first commit made

## Critical Review
- Can this be simpler? (yes = no unnecessary dependencies)
- Did I touch only what's needed? (yes = no premature configuration)
- What's still missing? (CI, deployment config, etc.)
EOF

# Copy language-specific templates
if [ -d "../templates/$LANGUAGE" ]; then
  echo "📋 Copying $LANGUAGE template..."
  cp -r ../templates/$LANGUAGE/* .
else
  echo "⚠️  No template for $LANGUAGE, using generic"
fi

# Special handling for Flutter: generate standard Flutter project structure
if [ "$LANGUAGE" = "flutter" ] && [ ! -f "pubspec.yaml" ]; then
  echo "⚡ Flutter detected but no template found. Please create Flutter project manually:"
  echo "   flutter create --org com.example --project-name aes_project ."
  echo "   Then run: make setup"
fi

# Generate language-specific Makefile based on template or generic
if [ -f "Makefile.template" ]; then
  cp Makefile.template Makefile
else
  cat > Makefile <<'MAKEFILE'
.PHONY: setup run test lint format build deploy check doctor metrics new-project help

# Include language config if exists
-include .aes/config.mk

# Set safe defaults if not defined
AES_LANGUAGE ?= unknown
AES_LINT ?= echo
AES_TEST ?= echo
AES_FORMAT ?= echo
AES_BUILD ?= echo
AES_RUN ?= echo

# Export to subprocesses
export AES_LANGUAGE AES_LINT AES_TEST AES_FORMAT AES_BUILD AES_RUN

setup:
	@echo "🔧 Setting up $(AES_LANGUAGE) project..."
	@chmod +x scripts/*.sh
	@./scripts/detect-language.sh
	@./scripts/install-deps.sh

run:
	@./scripts/run.sh

test:
	@./scripts/test.sh --coverage --verbose

lint:
	@./scripts/lint.sh --fix

format:
	@./scripts/format.sh

build:
	@./scripts/build.sh

deploy:
	@./scripts/deploy.sh

check: docs-check code-check test-check lint-check
	@./scripts/check.sh --strict
	@echo "✅ ALL QUALITY GATES PASSED"

docs-check:
	@./scripts/validate-docs.sh

code-check:
	@./scripts/validate-code.sh

test-check:
	@./scripts/validate-tests.sh

lint-check:
	@./scripts/lint.sh --no-fix

doctor:
	@./scripts/doctor.sh --all

metrics:
	@./scripts/metrics.sh --format=cli

roadmap:
	@./scripts/roadmap.sh

new-project:
	@echo "❌ Cannot scaffold within an AES project. Go up one directory."
	@exit 1

clean:
	@rm -rf tmp build dist coverage.* .coverage .pytest_cache target

help:
	@echo "AES Commands:"
	@echo "  make setup        - Install dependencies"
	@echo "  make run          - Run the app"
	@echo "  make test         - Run tests with coverage"
	@echo "  make lint         - Fix lint issues"
	@echo "  make format       - Format code"
	@echo "  make build        - Build artifacts"
	@echo "  make deploy       - Deploy (configure in scripts/deploy.sh)"
	@echo "  make check        - Run ALL quality gates"
	@echo "  make doctor       - System diagnostics"
	@echo "  make metrics      - Health dashboard"
	@echo "  make roadmap      - Show task status"

.DEFAULT_GOAL := help
MAKEFILE
fi

# Create .aes/config.mk with language-specific settings
mkdir -p .aes
cat > .aes/config.mk <<EOF
# Auto-generated by new-project scaffolding
AES_LANGUAGE=$LANGUAGE
EOF

# Add language-specific config (from templates if available)
if [ -f ".aes/config.mk.template" ]; then
  cat .aes/config.mk.template >> .aes/config.mk
else
  case "$LANGUAGE" in
  javascript)
    echo 'AES_LINT="npx eslint"' >> .aes/config.mk
    echo 'AES_TEST="jest"' >> .aes/config.mk
    echo 'AES_FORMAT="prettier --write"' >> .aes/config.mk
    ;;
  python)
    echo 'AES_LINT="ruff check"' >> .aes/config.mk
    echo 'AES_TEST="pytest"' >> .aes/config.mk
    echo 'AES_FORMAT="black"' >> .aes/config.mk
    ;;
  go)
    echo 'AES_LINT="go vet"' >> .aes/config.mk
    echo 'AES_TEST="go test"' >> .aes/config.mk
    echo 'AES_FORMAT="gofmt -w"' >> .aes/config.mk
    ;;
  rust)
    echo 'AES_LINT="cargo clippy"' >> .aes/config.mk
    echo 'AES_TEST="cargo test"' >> .aes/config.mk
    echo 'AES_FORMAT="cargo fmt --all"' >> .aes/config.mk
    ;;
  java)
    echo 'AES_LINT="./gradlew check"' >> .aes/config.mk
    echo 'AES_TEST="./gradlew test"' >> .aes/config.mk
    echo 'AES_FORMAT="google-java-format -i"' >> .aes/config.mk
    ;;
  php)
    echo 'AES_LINT="php -l"' >> .aes/config.mk
    echo 'AES_TEST="./vendor/bin/phpunit"' >> .aes/config.mk
    echo 'AES_FORMAT="php-cs-fixer fix"' >> .aes/config.mk
    ;;
  flutter)
    echo 'AES_LINT="flutter analyze"' >> .aes/config.mk
    echo 'AES_TEST="flutter test"' >> .aes/config.mk
    echo 'AES_FORMAT="dart format ."' >> .aes/config.mk
    echo 'AES_BUILD="flutter build apk"' >> .aes/config.mk
    echo 'AES_RUN="flutter run"' >> .aes/config.mk
    ;;
esac
fi

# Generate GitHub Actions CI
cat > .github/workflows/ci.yml <<'EOF'
name: AES Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  aes-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          chmod +x scripts/*.sh
          make setup

      - name: Run AES check
        run: make check

      - name: Run tests
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: always()
        with:
          fail_ci_if_error: false
EOF

# Create .gitignore
cat > .gitignore <<'EOF'
node_modules/
__pycache__/
*.pyc
.coverage
coverage.xml
coverage.out
target/
dist/
build/
.venv/
env/
.idea/
.vscode/
*.log
.DS_Store
.tmp/
aes-project/
EOF

# Add language-specific gitignore entries
case "$LANGUAGE" in
  go)
    echo "bin/" >> .gitignore
    ;;
  rust)
    echo "target/" >> .gitignore
    ;;
  java)
    echo ".gradle/" >> .gitignore
    echo "build/" >> .gitignore
    echo "out/" >> .gitignore
    ;;
  php)
    echo "vendor/" >> .gitignore
    echo "composer.lock" >> .gitignore
    ;;
esac

# Ensure scripts/ is copied if not from template
if [ ! -f "scripts/detect-language.sh" ]; then
  mkdir -p scripts
  cp -r ../scripts/*.sh scripts/
  chmod +x scripts/*.sh
fi

# Copy template task if not exists
if [ ! -f "docs/TASKS/task-template.md" ]; then
  mkdir -p docs/TASKS
  cp ../template/task.md docs/TASKS/task-template.md
fi

# Initialize git if not already
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git init
  git add .
  git commit -m "feat: initialize project with AES protocol"
fi

cd ..

echo ""
echo "✅ Project '$PROJECT_NAME' scaffolded successfully!"
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT_NAME"
echo "  2. Edit docs/VISION.md, docs/PERSONAS.md, docs/REQUIREMENTS.md"
echo "  3. Run: make setup"
echo "  4. Run: make check"
echo ""
echo "Files created:"
echo "  - docs/VISION.md, docs/PERSONAS.md, docs/REQUIREMENTS.md, docs/ROADMAP.md"
echo "  - docs/TASKS/01-initial-setup.md"
echo "  - Language-specific Makefile & source files"
echo "  - .github/workflows/ci.yml (GitHub Actions)"
echo "  - scripts/ (detection, validation, lint, test, etc.)"
echo ""

exit 0
  echo "Supported languages:"
  echo "  python, javascript, go, rust, java, php"
  exit 1
fi

echo "🏗️  Scaffolding new AES project: $PROJECT_NAME (language: $LANGUAGE)"
echo ""

# Validate name (alphanumeric, dash, underscore)
if [[ ! "$PROJECT_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "❌ Project name must be alphanumeric with dashes/underscores"
  exit 1
fi

# Check if directory exists
if [ -d "$PROJECT_NAME" ]; then
  echo "❌ Directory '$PROJECT_NAME' already exists"
  exit 1
fi

# Create directory structure
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

mkdir -p docs
mkdir -p src
mkdir -p tests
mkdir -p .github/workflows
mkdir -p .aes/plugins

# Copy and customize VISION.md (replace placeholders)
cat > docs/VISION.md <<EOF
# Vision

## Problem

[Describe the problem you're solving. Who is hurt by this? What happens if not solved?]

## Solution

[Describe your approach. How does it solve the problem? What makes it different?]

## Value

[Why this matters. Impact metrics. Success criteria.]
EOF

# Copy and customize PERSONAS.md
cat > docs/PERSONAS.md <<EOF
# Personas

## User

**Profile:** [Describe your user]

**Goals:**
- Goal 1
- Goal 2

**Needs:**
- Need 1
- Need 2

**Pain Points:**
- Pain 1
- Pain 2

## Maintainer

**Profile:** Engineer maintaining this codebase

**Goals:**
- Keep code clean and documented
- Ensure quality without friction

**Needs:**
- Clear testing strategy
- Automated quality gates
- Easy onboarding

**Tools:**
- AES (Aggressive Engineering System)
- \`make check\` for validation
EOF

# Copy and customize REQUIREMENTS.md
cat > docs/REQUIREMENTS.md <<EOF
# Requirements

## Functional

- [Feature 1 description]
- [Feature 2 description]

## Non-Functional

- Performance: [target]
- Security: [requirements]
- Maintainability: [guidelines]

## Constraints

- Language: $LANGUAGE
- Deployment: [target]
- Dependencies: [list]
EOF

# Copy and customize ROADMAP with first task
cat > docs/ROADMAP.md <<EOF
# Roadmap

## [HIGH] Initial Setup
- Impact: High
- Effort: Low
- Status: done

## [MEDIUM] First Feature
- Impact: Medium
- Effort: Medium
- Status: todo

## [LOW] Polish & Refine
- Impact: Low
- Effort: Low
- Status: todo

---
*Generated by AES scaffolding*
EOF

# Create base task template
mkdir -p docs/TASKS
cat > docs/TASKS/01-initial-setup.md <<'EOF'
# Task: Initial project setup

## Goal
Establish working project with AES quality gates passing.

## Hostile Analysis
- What assumptions are we making about the runtime?
- What could break in deployment?
- Is this the simplest way to achieve the goal?
- Are there dependencies that could cause issues?

## Proposed Solution
1. Follow language-specific setup guide
2. Write simple "hello world" to verify toolchain
3. Ensure `make check` passes

## Surgical Plan
1. Create minimal src/main.$LANG → verify: compiles/imports
2. Create tests → verify: `make test` passes (or skips gracefully)
3. Configure linter/formatter → verify: `make lint` passes
4. Update docs with actual tool versions → verify: `make doctor` shows no issues

## Validation
- [ ] Project builds without errors
- [ ] `make check` passes (or allows TODOs for unimplemented features)
- [ ] All docs exist and are filled (VISION, PERSONAS, REQUIREMENTS, ROADMAP)
- [ ] Git initialized, first commit made

## Critical Review
- Can this be simpler? (yes = no unnecessary dependencies)
- Did I touch only what's needed? (yes = no premature configuration)
- What's still missing? (CI, deployment config, etc.)
EOF

# Generate language-specific Makefile based on template or generic
if [ -f "templates/$(LANGUAGE)/Makefile" ]; then
  cp templates/$LANGUAGE/Makefile ./
else
  cat > Makefile <<'MAKEFILE'
.PHONY: setup run test lint format build deploy check doctor metrics new-project help

# Include language config if exists
-include .aes/config.mk

# Set safe defaults if not defined
AES_LANGUAGE ?= unknown
AES_LINT ?= echo
AES_TEST ?= echo
AES_FORMAT ?= echo
AES_BUILD ?= echo
AES_RUN ?= echo

# Export to subprocesses
export AES_LANGUAGE AES_LINT AES_TEST AES_FORMAT AES_BUILD AES_RUN

setup:
	@echo "🔧 Setting up $(AES_LANGUAGE) project..."
	@chmod +x scripts/*.sh
	@./scripts/detect-language.sh
	@./scripts/install-deps.sh

run:
	@./scripts/run.sh

test:
	@./scripts/test.sh --coverage --verbose

lint:
	@./scripts/lint.sh --fix

format:
	@./scripts/format.sh

build:
	@./scripts/build.sh

deploy:
	@./scripts/deploy.sh

check: docs-check code-check test-check lint-check
	@./scripts/check.sh --strict
	@echo "✅ ALL QUALITY GATES PASSED"

docs-check:
	@./scripts/validate-docs.sh

code-check:
	@./scripts/validate-code.sh

test-check:
	@./scripts/validate-tests.sh

lint-check:
	@./scripts/lint.sh --no-fix

doctor:
	@./scripts/doctor.sh --all

metrics:
	@./scripts/metrics.sh --format=cli

roadmap:
	@./scripts/roadmap.sh

new-project:
	@echo "❌ Cannot scaffold within an AES project. Go up one directory."
	@exit 1

clean:
	@rm -rf tmp build dist coverage.* .coverage .pytest_cache target

help:
	@echo "AES Commands:"
	@echo "  make setup        - Install dependencies"
	@echo "  make run          - Run the app"
	@echo "  make test         - Run tests with coverage"
	@echo "  make lint         - Fix lint issues"
	@echo "  make format       - Format code"
	@echo "  make build        - Build artifacts"
	@echo "  make deploy       - Deploy (configure in scripts/deploy.sh)"
	@echo "  make check        - Run ALL quality gates"
	@echo "  make doctor       - System diagnostics"
	@echo "  make metrics      - Health dashboard"
	@echo "  make roadmap      - Show task status"

.DEFAULT_GOAL := help
MAKEFILE
fi

# Detect language and customize Makefile
echo ""
echo "Configuring Makefile for $LANGUAGE..."
case "$LANGUAGE" in

  javascript)
    cat > src/index.js <<'EOF'
// Main entry point
console.log('Hello from AES project!');
module.exports = { main: () => console.log('Running...') };
EOF

    cat > package.json <<'EOF'
{
  "name": "aes-project",
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "start": "node src/index.js",
    "test": "jest --coverage",
    "lint": "eslint . --ext .js,.ts",
    "format": "prettier --write ."
  },
  "devDependencies": {
    "jest": "^29.0.0",
    "eslint": "^8.0.0",
    "prettier": "^3.0.0"
  }
}
EOF
    ;;

  python)
    cat > pyproject.toml <<'EOF'
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aes-project"
version = "0.1.0"
description = "AES-managed Python project"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=src --cov-report=xml --cov-report=term"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I"]
EOF

    mkdir -p src
    cat > src/__init__.py <<'EOF'
"""AES Project Package"""
__version__ = "0.1.0"
EOF

    cat > src/main.py <<'EOF'
"""Main application entry point."""
def main():
    print("Hello from AES project!")

if __name__ == "__main__":
    main()
EOF
    ;;

  go)
    cat > go.mod <<'EOF
module aes-project

go 1.21
EOF

    mkdir -p src
    cat > src/main.go <<'EOF'
package main

import "fmt"

func main() {
    fmt.Println("Hello from AES project!")
}
EOF
    ;;

  rust)
    cat > Cargo.toml <<'EOF'
[package]
name = "aes-project"
version = "0.1.0"
edition = "2021"

[dependencies]
EOF

    mkdir -p src
    cat > src/main.rs <<'EOF'
fn main() {
    println!("Hello from AES project!");
}
EOF
    ;;

  java)
    cat > build.gradle <<'EOF'
plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'
}

application {
    mainClass = 'com.example.App'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
}
EOF

    mkdir -p src/main/java/com/example
    cat > src/main/java/com/example/App.java <<'EOF'
package com.example;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello from AES project!");
    }
}
EOF
    ;;

  php)
    cat > composer.json <<'EOF'
{
    "name": "aes/project",
    "require": {}
}
EOF

    mkdir -p src
    cat > src/index.php <<'EOF'
<?php
echo "Hello from AES project!\n";
EOF
    ;;

  *)
    echo "⚠️  Unknown language: $LANGUAGE"
    echo "Creating generic templates only..."
    cat > Makefile <<'MAKEFILE'
.PHONY: setup run test lint format build deploy check doctor metrics

setup:
	@echo "Setup complete. Edit scripts/*.sh for your project."

run:
	@echo "Edit scripts/run.sh to run your app"

test:
	@echo "Edit scripts/test.sh to run your tests"

lint:
	@echo "Edit scripts/lint.sh to lint your code"

format:
	@echo "Edit scripts/format.sh to format your code"

check:
	@./scripts/check.sh

doctor:
	@./scripts/doctor.sh

metrics:
	@./scripts/metrics.sh

deploy:
	@echo "Edit scripts/deploy.sh for deployment"

clean:
	@rm -rf tmp build dist

MAKEFILE
    ;;
esac

# Create .aes/config.mk with language-specific settings
mkdir -p .aes
cat > .aes/config.mk <<EOF
# Auto-generated by AES scaffolding
AES_LANGUAGE=$LANGUAGE
EOF

case "$LANGUAGE" in
  javascript) echo 'AES_LINT="npx eslint"' >> .aes/config.mk ;;
  python) echo 'AES_LINT="ruff check"' >> .aes/config.mk ;;
  go) echo 'AES_LINT="go vet"' >> .aes/config.mk ;;
  rust) echo 'AES_LINT="cargo clippy"' >> .aes/config.mk ;;
  java) echo 'AES_LINT="./gradlew check"' >> .aes/config.mk ;;
  php) echo 'AES_LINT="php -l"' >> .aes/config.mk ;;
esac

# Generate GitHub Actions CI
cat > .github/workflows/ci.yml <<'EOF'
name: AES Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  aes-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          chmod +x scripts/*.sh
          make setup

      - name: Run AES check
        run: make check

      - name: Run tests
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: always()
        with:
          fail_ci_if_error: false
EOF

# Create .gitignore
cat > .gitignore <<'EOF'
node_modules/
__pycache__/
*.pyc
.coverage
coverage.xml
coverage.out
target/
dist/
build/
.venv/
env/
.idea/
.vscode/
*.log
.DS_Store
.tmp/
aes-project/
EOF

# Create empty scripts dir if not copied
if [ ! -f "scripts/detect-language.sh" ]; then
  cp -r ../scripts .
  chmod +x scripts/*.sh
fi

# Copy default templates if missing
if [ ! -f "docs/TASKS/task-template.md" ]; then
  mkdir -p docs/TASKS
  cp ../template/task.md docs/TASKS/task-template.md
fi

# Initialize git if not already
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git init
  git add .
  git commit -m "feat: initialize project with AES protocol"
fi

cd ..

echo ""
echo "✅ Project '$PROJECT_NAME' scaffolded successfully!"
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT_NAME"
echo "  2. Edit docs/VISION.md, docs/PERSONAS.md, docs/REQUIREMENTS.md"
echo "  3. Run: make setup"
echo "  4. Run: make check"
echo ""
echo "Files created:"
echo "  - docs/VISION.md, docs/PERSONAS.md, docs/REQUIREMENTS.md, docs/ROADMAP.md"
echo "  - docs/TASKS/01-initial-setup.md"
echo "  - Language-specific Makefile & source files"
echo "  - .github/workflows/ci.yml (GitHub Actions)"
echo "  - scripts/ (detection, validation, lint, test, etc.)"
echo ""
